
// 365 versículos extraídos da Bíblia NVI (thiagobodruk/biblia)
// Cada versículo tem no máximo 95 caracteres para caber em 2 linhas
export const dailyWords = [
    { text: "O Senhor é o meu pastor; de nada terei falta.", reference: "Salmos 23:1" },
    { text: "Espere no Senhor. Seja forte! Coragem! Espere no Senhor.", reference: "Salmos 27:14" },
    { text: "Provem, e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!", reference: "Salmos 34:8" },
    { text: "O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido.", reference: "Salmos 34:18" },
    { text: "Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.", reference: "Salmos 37:4" },
    { text: "Entregue o seu caminho ao Senhor; confie nele, e ele agirá:", reference: "Salmos 37:5" },
    { text: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.", reference: "Salmos 46:1" },
    { text: "Deus nela está! Não será abalada! Deus vem em seu auxílio desde o romper da manhã.", reference: "Salmos 46:5" },
    { text: "Cria em mim um coração puro, ó Deus, e renova dentro de mim um espírito estável.", reference: "Salmos 51:10" },
    { text: "Devolve-me a alegria da tua salvação e sustenta-me com um espírito pronto a obedecer.", reference: "Salmos 51:12" },
    { text: "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso", reference: "Salmos 91:1" },
    { text: "pode dizer ao Senhor: Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.", reference: "Salmos 91:2" },
    { text: "Mil poderão cair ao seu lado, dez mil à sua direita, mas nada o atingirá.", reference: "Salmos 91:7" },
    { text: "Aclamem o Senhor todos os habitantes da terra!", reference: "Salmos 100:1" },
    { text: "Prestem culto ao Senhor com alegria; entrem na sua presença com cânticos alegres.", reference: "Salmos 100:2" },
    { text: "Bendiga ao Senhor a minha alma! Bendiga ao Senhor todo o meu ser!", reference: "Salmos 103:1" },
    { text: "Bendiga ao Senhor a minha alma! Não esqueça de nenhuma de suas bênçãos!", reference: "Salmos 103:2" },
    { text: "O Senhor é compassivo e misericordioso, mui paciente e cheio de amor.", reference: "Salmos 103:8" },
    { text: "A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho.", reference: "Salmos 119:105" },
    { text: "Levanto os meus olhos para os montes e pergunto: De onde me vem o socorro?", reference: "Salmos 121:1" },
    { text: "O meu socorro vem do Senhor, que fez os céus e a terra.", reference: "Salmos 121:2" },
    { text: "O Senhor é o seu protetor; como sombra que o protege, ele está à sua direita.", reference: "Salmos 121:5" },
    { text: "O Senhor o protegerá de todo o mal, protegerá a sua vida.", reference: "Salmos 121:7" },
    { text: "O Senhor protegerá a sua saída e a sua chegada, desde agora e para sempre.", reference: "Salmos 121:8" },
    { text: "Como é bom e agradável quando os irmãos convivem em união!", reference: "Salmos 133:1" },
    { text: "Dêem graças ao Senhor, porque ele é bom. O seu amor dura para sempre!", reference: "Salmos 136:1" },
    { text: "Senhor, tu me sondas e me conheces.", reference: "Salmos 139:1" },
    { text: "Tu me cercas, por trás e pela frente, e pões a tua mão sobre mim.", reference: "Salmos 139:5" },
    { text: "Grande é o Senhor e digno de ser louvado; sua grandeza não tem limites.", reference: "Salmos 145:3" },
    { text: "O Senhor é misericordioso e compassivo, paciente e transbordante de amor.", reference: "Salmos 145:8" },
    { text: "O Senhor é bom para todos; a sua compaixão alcança todas as suas criaturas.", reference: "Salmos 145:9" },
    { text: "O Senhor ampara todos os que caem e levanta todos os que estão prostrados.", reference: "Salmos 145:14" },
    { text: "O Senhor é justo em todos os seus caminhos e é bondoso em tudo o que faz.", reference: "Salmos 145:17" },
    { text: "O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade.", reference: "Salmos 145:18" },
    { text: "Aleluia! Como é bom cantar louvores ao nosso Deus! Como é agradável e próprio louvá-lo!", reference: "Salmos 147:1" },
    { text: "Só ele cura os de coração quebrantado e cuida das suas feridas.", reference: "Salmos 147:3" },
    { text: "Grande é o nosso Soberano e tremendo é o seu poder; é impossível medir o seu entendimento.", reference: "Salmos 147:5" },
    { text: "Ensina-nos a contar os nossos dias para que o nosso coração alcance sabedoria.", reference: "Salmos 90:12" },
    { text: "Senhor, tu és a minha porção e o meu cálice; és tu que garantes o meu futuro.", reference: "Salmos 16:5" },
    { text: "Eu te amo, ó Senhor, minha força.", reference: "Salmos 18:1" },
    { text: "Os céus declaram a glória de Deus; o firmamento proclama a obra das suas mãos.", reference: "Salmos 19:1" },
    { text: "Do Senhor é a terra e tudo o que nela existe, o mundo e os que nele vivem;", reference: "Salmos 24:1" },
    { text: "O Senhor dá força ao seu povo; o Senhor dá a seu povo a bênção da paz.", reference: "Salmos 29:11" },
    { text: "Como é feliz a nação que tem o Senhor como Deus, o povo que ele escolheu para lhe pertencer!", reference: "Salmos 33:12" },
    { text: "Como é precioso o teu amor, ó Deus! Os homens encontram refúgio à sombra das tuas asas.", reference: "Salmos 36:7" },
    { text: "Mas eu, quando estiver com medo, confiarei em ti.", reference: "Salmos 56:3" },
    { text: "Bendito seja o Senhor, Deus, nosso Salvador, que cada dia suporta as nossas cargas. Pausa", reference: "Salmos 68:19" },
    { text: "Em ti, Senhor, busquei refúgio; nunca permitas que eu seja humilhado.", reference: "Salmos 71:1" },
    { text: "A quem tenho nos céus senão a ti? E na terra, nada mais desejo além de estar junto a ti.", reference: "Salmos 73:25" },
    { text: "Como são felizes os que habitam em tua casa; louvam-te sem cessar! Pausa", reference: "Salmos 84:4" },
    { text: "Os justos florescerão como a palmeira, crescerão como o cedro do Líbano;", reference: "Salmos 92:12" },
    { text: "Venham! Adoremos prostrados e ajoelhemos diante do Senhor, o nosso Criador;", reference: "Salmos 95:6" },
    { text: "Cantem ao Senhor um novo cântico; cantem ao Senhor, todos os habitantes da terra!", reference: "Salmos 96:1" },
    { text: "Cantem ao Senhor, bendigam o seu nome; cada dia proclamem a sua salvação!", reference: "Salmos 96:2" },
    { text: "O Senhor reina! Exulte a terra e alegrem-se as regiões costeiras distantes.", reference: "Salmos 97:1" },
    { text: "Dêem graças ao Senhor porque ele é bom; o seu amor dura para sempre.", reference: "Salmos 107:1" },
    { text: "Ele fez proclamar as suas maravilhas; o Senhor é misericordioso e compassivo.", reference: "Salmos 111:4" },
    { text: "Quem é como o Senhor, o nosso Deus, que reina em seu trono nas alturas,", reference: "Salmos 113:5" },
    { text: "O Senhor é a minha força e o meu cântico; ele é a minha salvação.", reference: "Salmos 118:14" },
    { text: "Dá-me entendimento, para que eu guarde a tua lei e a ela obedeça de todo o coração.", reference: "Salmos 119:34" },
    { text: "Tu és a minha herança, Senhor; prometi obedecer às tuas palavras.", reference: "Salmos 119:57" },
    { text: "Como são doces para o meu paladar as tuas palavras! Mais do que o mel para a minha boca!", reference: "Salmos 119:103" },
    { text: "Eu clamo pelo Senhor na minha angústia, e ele me responde.", reference: "Salmos 120:1" },
    { text: "O nosso socorro está no nome do Senhor, que fez os céus e a terra.", reference: "Salmos 124:8" },
    { text: "Sim, coisas grandiosas fez o Senhor por nós, por isso estamos alegres.", reference: "Salmos 126:3" },
    { text: "Aleluia! Louvem o nome do Senhor; louvem-no, servos do Senhor,", reference: "Salmos 135:1" },
    { text: "Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece as minhas inquietações.", reference: "Salmos 139:23" },
    { text: "Saibam que o Senhor escolheu o piedoso; o Senhor ouvirá quando eu o invocar.", reference: "Salmos 4:3" },
    { text: "Do Senhor vem o livramento. A tua bênção está sobre o teu povo. Pausa", reference: "Salmos 3:8" },
    { text: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento;", reference: "Provérbios 3:5" },
    { text: "reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.", reference: "Provérbios 3:6" },
    { text: "A bênção do Senhor traz riqueza, e não inclui dor alguma.", reference: "Provérbios 10:22" },
    { text: "Todo o que ama a disciplina ama o conhecimento, mas aquele que odeia a repreensão é tolo.", reference: "Provérbios 12:1" },
    { text: "A esperança que se retarda deixa o coração doente, mas o anseio satisfeito é árvore de vida.", reference: "Provérbios 13:12" },
    { text: "A resposta calma desvia a fúria, mas a palavra ríspida desperta a ira.", reference: "Provérbios 15:1" },
    { text: "É melhor ter pouco com retidão do que muito com injustiça.", reference: "Provérbios 16:8" },
    { text: "O nome do Senhor é uma torre forte; os justos correm para ela e estão seguros.", reference: "Provérbios 18:10" },
    { text: "Meu filho, dê-me o seu coração; mantenha os seus olhos em meus caminhos,", reference: "Provérbios 23:26" },
    { text: "Para tudo há uma ocasião, e um tempo para cada propósito debaixo do céu:", reference: "Eclesiastes 3:1" },
    { text: "Confiem para sempre no Senhor, pois o Senhor, somente o Senhor, é a Rocha eterna.", reference: "Isaías 26:4" },
    { text: "A glória do Senhor será revelada, e, juntos, todos a verão. Pois é o Senhor quem fala\".", reference: "Isaías 40:5" },
    { text: "Ele fortalece ao cansado e dá grande vigor ao que está sem forças.", reference: "Isaías 40:29" },
    { text: "Busquem o Senhor enquanto se pode achá-lo; clamem por ele enquanto está perto.", reference: "Isaías 55:6" },
    { text: "\"Mas bendito é o homem cuja confiança está no Senhor, cuja confiança nele está.", reference: "Jeremias 17:7" },
    { text: "o Senhor lhe apareceu no passado, dizendo: \"Eu a amei com amor eterno; com amor leal a atrai.", reference: "Jeremias 31:3" },
    { text: "Renovam-se cada manhã; grande é a tua fidelidade!", reference: "Lamentações 3:23" },
    { text: "Digo a mim mesmo: A minha porção é o Senhor; portanto, nele porei a minha esperança.", reference: "Lamentações 3:24" },
    { text: "O Senhor é bom para com aqueles cuja esperança está nele, para com aqueles que o buscam;", reference: "Lamentações 3:25" },
    { text: "O SENHOR é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam,", reference: "Naum 1:7" },
    { text: "\"O Senhor te abençoe e te guarde;", reference: "Números 6:24" },
    { text: "o Senhor volte para ti o seu rosto e te dê paz.", reference: "Números 6:26" },
    { text: "O Senhor lutará por vocês; tão-somente acalmem-se\".", reference: "Êxodo 14:14" },
    { text: "\"Bem-aventurados os pobres em espírito, pois deles é o Reino dos céus.", reference: "Mateus 5:3" },
    { text: "Bem-aventurados os que choram, pois serão consolados.", reference: "Mateus 5:4" },
    { text: "Bem-aventurados os que têm fome e sede de justiça, pois serão satisfeitos.", reference: "Mateus 5:6" },
    { text: "Bem-aventurados os misericordiosos, pois obterão misericórdia.", reference: "Mateus 5:7" },
    { text: "Bem-aventurados os puros de coração, pois verão a Deus.", reference: "Mateus 5:8" },
    { text: "Bem-aventurados os pacificadores, pois serão chamados filhos de Deus.", reference: "Mateus 5:9" },
    { text: "\"Vocês são a luz do mundo. Não se pode esconder uma cidade construída sobre um monte.", reference: "Mateus 5:14" },
    { text: "Pois onde estiver o seu tesouro, aí também estará o seu coração.", reference: "Mateus 6:21" },
    { text: "\"Não julguem, para que vocês não sejam julgados.", reference: "Mateus 7:1" },
    { text: "\"Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta lhes será aberta.", reference: "Mateus 7:7" },
    { text: "\"Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.", reference: "Mateus 11:28" },
    { text: "Pois o meu jugo é suave e o meu fardo é leve\".", reference: "Mateus 11:30" },
    { text: "Pois onde se reunirem dois ou três em meu nome, ali eu estou no meio deles\".", reference: "Mateus 18:20" },
    { text: "\"Se podes? \", disse Jesus. \"Tudo é possível àquele que crê. \"", reference: "Marcos 9:23" },
    { text: "Pois nada é impossível para Deus\".", reference: "Lucas 1:37" },
    { text: "A sua misericórdia estende-se aos que o temem, de geração em geração.", reference: "Lucas 1:50" },
    { text: "\"Louvado seja o Senhor, o Deus de Israel, porque visitou e redimiu o seu povo.", reference: "Lucas 1:68" },
    { text: "Hoje, na cidade de Davi, lhes nasceu o Salvador que é Cristo, o Senhor.", reference: "Lucas 2:11" },
    { text: "\"Glória a Deus nas alturas, e paz na terra aos homens aos quais ele concede o seu favor\".", reference: "Lucas 2:14" },
    { text: "Sejam misericordiosos, assim como o Pai de vocês é misericordioso\".", reference: "Lucas 6:36" },
    { text: "Pois todo o que pede, recebe; o que busca, encontra; e àquele que bate, a porta será aberta.", reference: "Lucas 11:10" },
    { text: "\"Não tenham medo, pequeno rebanho, pois foi do agrado do Pai dar-lhes o Reino.", reference: "Lucas 12:32" },
    { text: "A luz brilha nas trevas, e as trevas não a derrotaram.", reference: "João 1:5" },
    { text: "Mas ele lhes disse: \"Sou eu! Não tenham medo! \"", reference: "João 6:20" },
    { text: "Simão Pedro lhe respondeu: \"Senhor, para quem iremos? Tu tens as palavras de vida eterna.", reference: "João 6:68" },
    { text: "E conhecerão a verdade, e a verdade os libertará\".", reference: "João 8:32" },
    { text: "Eu sou a porta; quem entra por mim será salvo. Entrará e sairá, e encontrará pastagem.", reference: "João 10:9" },
    { text: "\"Eu sou o bom pastor. O bom pastor dá a sua vida pelas ovelhas.", reference: "João 10:11" },
    { text: "Com isso todos saberão que vocês são meus discípulos, se vocês se amarem uns aos outros\".", reference: "João 13:35" },
    { text: "\"Não se perturbe o coração de vocês. Creiam em Deus; creiam também em mim.", reference: "João 14:1" },
    { text: "Respondeu Jesus: \"Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim.", reference: "João 14:6" },
    { text: "O meu mandamento é este: amem-se uns aos outros como eu os amei.", reference: "João 15:12" },
    { text: "Portanto, agora já não há condenação para os que estão em Cristo Jesus,", reference: "Romanos 8:1" },
    { text: "porque todos os que são guiados pelo Espírito de Deus são filhos de Deus.", reference: "Romanos 8:14" },
    { text: "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós?", reference: "Romanos 8:31" },
    { text: "Mas, em todas estas coisas somos mais que vencedores, por meio daquele que nos amou.", reference: "Romanos 8:37" },
    { text: "porque \"todo aquele que invocar o nome do Senhor será salvo\".", reference: "Romanos 10:13" },
    { text: "Pois dele, por ele e para ele são todas as coisas. A ele seja a glória para sempre! Amém.", reference: "Romanos 11:36" },
    { text: "Alegrem-se com os que se alegram; chorem com os que choram.", reference: "Romanos 12:15" },
    { text: "O amor não pratica o mal contra o próximo. Portanto, o amor é o cumprimento da lei.", reference: "Romanos 13:10" },
    { text: "Pois o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo;", reference: "Romanos 14:17" },
    { text: "Eu plantei, Apolo regou, mas Deus é quem fazia crescer;", reference: "1 Coríntios 3:6" },
    { text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", reference: "1 Coríntios 13:4" },
    { text: "Tudo sofre, tudo crê, tudo espera, tudo suporta.", reference: "1 Coríntios 13:7" },
    { text: "Mas graças a Deus, que nos dá a vitória por meio de nosso Senhor Jesus Cristo.", reference: "1 Coríntios 15:57" },
    { text: "Estejam vigilantes, mantenham-se firmes na fé, sejam homens de coragem, sejam fortes.", reference: "1 Coríntios 16:13" },
    { text: "Porque vivemos por fé, e não pelo que vemos.", reference: "2 Coríntios 5:7" },
    { text: "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade,", reference: "Gálatas 5:22" },
    { text: "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus;", reference: "Efésios 2:8" },
    { text: "Vistam toda a armadura de Deus, para poderem ficar firmes contra as ciladas do diabo,", reference: "Efésios 6:11" },
    { text: "Alegrem-se sempre no Senhor. Novamente direi: alegrem-se!", reference: "Filipenses 4:4" },
    { text: "Tudo posso naquele que me fortalece.", reference: "Filipenses 4:13" },
    { text: "Pois ele nos resgatou do domínio das trevas e nos transportou para o Reino do seu Filho amado,", reference: "Colossenses 1:13" },
    { text: "Ele é antes de todas as coisas, e nele tudo subsiste.", reference: "Colossenses 1:17" },
    { text: "Acima de tudo, porém, revistam-se do amor, que é o elo perfeito.", reference: "Colossenses 3:14" },
    { text: "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens,", reference: "Colossenses 3:23" },
    { text: "Orem continuamente.", reference: "1 Tessalonicenses 5:17" },
    { text: "mas ponham à prova todas as coisas e fiquem com o que é bom.", reference: "1 Tessalonicenses 5:21" },
    { text: "Aquele que os chama é fiel, e fará isso.", reference: "1 Tessalonicenses 5:24" },
    { text: "Mas o Senhor é fiel; ele os fortalecerá e os guardará do Maligno.", reference: "2 Tessalonicenses 3:3" },
    { text: "pois nada trouxemos para este mundo e dele nada podemos levar;", reference: "1 Timóteo 6:7" },
    { text: "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.", reference: "2 Timóteo 1:7" },
    { text: "Combati o bom combate, terminei a corrida, guardei a fé.", reference: "2 Timóteo 4:7" },
    { text: "Porque a graça de Deus se manifestou salvadora a todos os homens.", reference: "Tito 2:11" },
    { text: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.", reference: "Hebreus 11:1" },
    { text: "Sejam praticantes da palavra, e não apenas ouvintes, enganando-se a si mesmos.", reference: "Tiago 1:22" },
    { text: "Humilhem-se diante do Senhor, e ele os exaltará.", reference: "Tiago 4:10" },
    { text: "pois está escrito: \"Sejam santos, porque eu sou santo\".", reference: "1 Pedro 1:16" },
    { text: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.", reference: "1 Pedro 5:7" },
    { text: "Filhinhos, não amemos de palavra nem de boca, mas em ação e em verdade.", reference: "1 João 3:18" },
    { text: "Quem não ama não conhece a Deus, porque Deus é amor.", reference: "1 João 4:8" },
    { text: "Nós amamos porque ele nos amou primeiro.", reference: "1 João 4:19" },
    { text: "O que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.", reference: "1 João 5:4" },
    { text: "Ao contrário, sua satisfação está na lei do Senhor, e nessa lei medita dia e noite.", reference: "Salmos 1:2" },
    { text: "Não é o caso dos ímpios! São como palha que o vento leva.", reference: "Salmos 1:4" },
    { text: "Por isso os ímpios não resistirão no julgamento, nem os pecadores na comunidade dos justos.", reference: "Salmos 1:5" },
    { text: "Pois o Senhor aprova o caminho dos justos, mas o caminho dos ímpios leva à destruição!", reference: "Salmos 1:6" },
    { text: "Por que se amotinam as nações e os povos tramam em vão?", reference: "Salmos 2:1" },
    { text: "\"Façamos em pedaços as suas correntes, lancemos de nós as suas algemas! \"", reference: "Salmos 2:3" },
    { text: "Do seu trono nos céus o Senhor põe-se a rir e caçoa deles.", reference: "Salmos 2:4" },
    { text: "Em sua ira os repreende e em seu furor os aterroriza, dizendo:", reference: "Salmos 2:5" },
    { text: "\"Eu mesmo estabeleci o meu rei em Sião, no meu santo monte\".", reference: "Salmos 2:6" },
    { text: "Proclamarei o decreto do Senhor: Ele me disse: \"Tu és meu filho; eu hoje te gerei.", reference: "Salmos 2:7" },
    { text: "Pede-me, e te darei as nações como herança e os confins da terra como tua propriedade.", reference: "Salmos 2:8" },
    { text: "Tu as quebrarás com vara de ferro e as despedaçarás como a um vaso de barro\".", reference: "Salmos 2:9" },
    { text: "Por isso, ó reis, sejam prudentes; aceitem a advertência, autoridades da terra.", reference: "Salmos 2:10" },
    { text: "Adorem ao Senhor com temor; exultem com tremor.", reference: "Salmos 2:11" },
    { text: "Senhor, muitos são os meus adversários! Muitos se rebelam contra mim!", reference: "Salmos 3:1" },
    { text: "São muitos os que dizem a meu respeito: \"Deus nunca o salvará! \" Pausa", reference: "Salmos 3:2" },
    { text: "Ao Senhor clamo em alta voz, e do seu santo monte ele me responde. Pausa", reference: "Salmos 3:4" },
    { text: "Eu me deito e durmo, e torno a acordar, porque é o Senhor que me sustém.", reference: "Salmos 3:5" },
    { text: "Não me assustam os milhares que me cercam.", reference: "Salmos 3:6" },
    { text: "Quando vocês ficarem irados, não pequem; ao deitar-se reflitam nisso, e aquietem-se. Pausa", reference: "Salmos 4:4" },
    { text: "Ofereçam sacrifícios como Deus exige e confiem no Senhor.", reference: "Salmos 4:5" },
    { text: "Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança.", reference: "Salmos 4:8" },
    { text: "Escuta, Senhor, as minhas palavras, considera o meu gemer.", reference: "Salmos 5:1" },
    { text: "Atenta para o meu grito de socorro, meu Rei e meu Deus, pois é a ti que imploro.", reference: "Salmos 5:2" },
    { text: "Tu não és um Deus que tenha prazer na injustiça; contigo o mal não pode habitar.", reference: "Salmos 5:4" },
    { text: "Os arrogantes não são aceitos na tua presença; odeias todos os que praticam o mal.", reference: "Salmos 5:5" },
    { text: "Destróis os mentirosos; os assassinos e os traiçoeiros o Senhor detesta.", reference: "Salmos 5:6" },
    { text: "Pois tu, Senhor, abençoas o justo; o teu favor o protege como um escudo.", reference: "Salmos 5:12" },
    { text: "Senhor, não me castigues na tua ira nem me disciplines no teu furor.", reference: "Salmos 6:1" },
    { text: "Misericórdia, Senhor, pois vou desfalecendo! Cura-me, Senhor, pois os meus ossos tremem:", reference: "Salmos 6:2" },
    { text: "Todo o meu ser estremece. Até quando, Senhor, até quando?", reference: "Salmos 6:3" },
    { text: "Volta-te, Senhor, e livra-me; salva-me por causa do teu amor leal.", reference: "Salmos 6:4" },
    { text: "Quem morreu não se lembra de ti. Entre os mortos, quem te louvará?", reference: "Salmos 6:5" },
    { text: "Os meus olhos se consomem de tristeza; fraquejam por causa de todos os meus adversários.", reference: "Salmos 6:7" },
    { text: "Afastem-se de mim todos vocês que praticam o mal, porque o Senhor ouviu o meu choro.", reference: "Salmos 6:8" },
    { text: "O Senhor ouviu a minha súplica; o Senhor aceitou a minha oração.", reference: "Salmos 6:9" },
    { text: "Serão humilhados e aterrorizados todos os meus inimigos; frustrados, recuarão de repente.", reference: "Salmos 6:10" },
    { text: "Senhor meu Deus, em ti me refugio; salva-me e livra-me de todos os que me perseguem,", reference: "Salmos 7:1" },
    { text: "para que, como leões, não me dilacerem nem me despedacem, sem que ninguém me livre.", reference: "Salmos 7:2" },
    { text: "Senhor meu Deus, se assim procedi, se nas minhas mãos há injustiça,", reference: "Salmos 7:3" },
    { text: "se fiz algum mal a um amigo ou se poupei sem motivo o meu adversário,", reference: "Salmos 7:4" },
    { text: "Reúnam-se os povos ao teu redor. Das alturas reina sobre eles.", reference: "Salmos 7:7" },
    { text: "O meu escudo está nas mãos de Deus, que salva o reto de coração.", reference: "Salmos 7:10" },
    { text: "Deus é um juiz justo, um Deus que manifesta cada dia o seu furor.", reference: "Salmos 7:11" },
    { text: "Se o homem não se arrepende, Deus afia a sua espada, arma o seu arco e o aponta,", reference: "Salmos 7:12" },
    { text: "prepara as suas armas mortais e faz de suas setas flechas flamejantes.", reference: "Salmos 7:13" },
    { text: "Quem gera a maldade, concebe sofrimento e dá à luz a desilusão.", reference: "Salmos 7:14" },
    { text: "Quem cava um buraco e o aprofunda cairá nessa armadilha que fez.", reference: "Salmos 7:15" },
    { text: "Sua maldade se voltará contra ele; sua violência cairá sobre a sua própria cabeça.", reference: "Salmos 7:16" },
    { text: "Darei graças ao Senhor por sua justiça; Ao nome do Senhor Altíssimo cantarei louvores.", reference: "Salmos 7:17" },
    { text: "Quando contemplo os teus céus, obra dos teus dedos, a lua e as estrelas que ali firmaste,", reference: "Salmos 8:3" },
    { text: "Tu o fizeste um pouco menor do que os seres celestiais e o coroaste de glória e de honra.", reference: "Salmos 8:5" },
    { text: "Tu o fizeste dominar sobre as obras das tuas mãos; sob os seus pés tudo puseste:", reference: "Salmos 8:6" },
    { text: "Todos os rebanhos e manadas, e até os animais selvagens,", reference: "Salmos 8:7" },
    { text: "as aves do céu, os peixes do mar e tudo o que percorre as veredas dos mares.", reference: "Salmos 8:8" },
    { text: "Senhor, Senhor nosso, como é majestoso o teu nome em toda a terra!", reference: "Salmos 8:9" },
    { text: "Senhor, quero dar-te graças de todo o coração e falar de todas as tuas maravilhas.", reference: "Salmos 9:1" },
    { text: "Em ti quero alegrar-me e exultar, e cantar louvores ao teu nome, ó Altíssimo.", reference: "Salmos 9:2" },
    { text: "Quando os meus inimigos contigo se defrontam, tropeçam e são destruídos.", reference: "Salmos 9:3" },
    { text: "Repreendeste as nações e destruíste os ímpios; para todo o sempre apagaste o nome deles.", reference: "Salmos 9:5" },
    { text: "O Senhor reina para sempre; estabeleceu o seu trono para julgar.", reference: "Salmos 9:7" },
    { text: "Ele mesmo julga o mundo com justiça; governa os povos com retidão.", reference: "Salmos 9:8" },
    { text: "O Senhor é refúgio para os oprimidos, uma torre segura na hora da adversidade.", reference: "Salmos 9:9" },
    { text: "Os que conhecem o teu nome confiam em ti, pois tu, Senhor, jamais abandonas os que te buscam.", reference: "Salmos 9:10" },
    { text: "Cantem louvores ao Senhor, que reina em Sião; proclamem entre as nações os seus feitos.", reference: "Salmos 9:11" },
    { text: "Aquele que pede contas do sangue derramado não esquece; ele não ignora o clamor dos oprimidos.", reference: "Salmos 9:12" },
    { text: "Caíram as nações na cova que abriram; os seus pés ficaram presos no laço que esconderam.", reference: "Salmos 9:15" },
    { text: "Voltem os ímpios ao pó, todas as nações que se esquecem de Deus!", reference: "Salmos 9:17" },
    { text: "Mas os pobres nunca serão esquecidos, nem se frustrará a esperança dos necessitados.", reference: "Salmos 9:18" },
    { text: "Infunde-lhes terror, Senhor; saibam as nações que não passam de seres humanos. Pausa", reference: "Salmos 9:20" },
    { text: "Senhor, por que estás tão longe? Por que te escondes em tempos de angústia?", reference: "Salmos 10:1" },
    { text: "Em sua arrogância o ímpio persegue o pobre, que é apanhado em suas tramas.", reference: "Salmos 10:2" },
    { text: "Ele se gaba de sua própria cobiça e, em sua ganância, amaldiçoa e insulta o Senhor.", reference: "Salmos 10:3" },
    { text: "Em sua presunção o ímpio não o busca; não há lugar para Deus em nenhum dos seus planos.", reference: "Salmos 10:4" },
    { text: "Sua boca está cheia de maldições, mentiras e ameaças; violência e maldade estão em sua língua.", reference: "Salmos 10:7" },
    { text: "Agachado, fica de tocaia; as suas vítimas caem em seu poder.", reference: "Salmos 10:10" },
    { text: "Pensa consigo mesmo: \"Deus se esqueceu; escondeu o rosto e nunca verá isto\".", reference: "Salmos 10:11" },
    { text: "Levanta-te, Senhor! Ergue a tua mão, ó Deus! Não te esqueças dos necessitados.", reference: "Salmos 10:12" },
    { text: "Por que o ímpio insulta a Deus, dizendo no seu íntimo: \"De nada me pedirás contas! \"?", reference: "Salmos 10:13" },
    { text: "O Senhor é rei para todo o sempre; da sua terra desapareceram os outros povos.", reference: "Salmos 10:16" },
    { text: "Tu, Senhor, ouves a súplica dos necessitados; tu os reanimas e atendes ao seu clamor.", reference: "Salmos 10:17" },
    { text: "Defendes o órfão e o oprimido, a fim de que o homem, que é pó, já não cause terror.", reference: "Salmos 10:18" },
    { text: "No Senhor me refugio. Como então vocês podem dizer-me: \"Fuja como um pássaro para os montes\"?", reference: "Salmos 11:1" },
    { text: "Quando os fundamentos estão sendo destruídos, que pode fazer o justo?", reference: "Salmos 11:3" },
    { text: "O Senhor prova o justo, mas o ímpio e a quem ama a injustiça, a sua alma odeia.", reference: "Salmos 11:5" },
    { text: "Pois o Senhor é justo, e ama a justiça; os retos verão a sua face.", reference: "Salmos 11:7" },
    { text: "Salva-nos, Senhor! Já não há quem seja fiel; já não se confia em ninguém entre os homens.", reference: "Salmos 12:1" },
    { text: "Cada um mente ao seu próximo; seus lábios bajuladores falam com segundas intenções.", reference: "Salmos 12:2" },
    { text: "Que o Senhor corte todos os lábios bajuladores e toda língua arrogante", reference: "Salmos 12:3" },
    { text: "As palavras do Senhor são puras, são como prata purificada num forno, sete vezes refinada.", reference: "Salmos 12:6" },
    { text: "Senhor, tu nos guardarás seguros, e dessa gente nos protegerás para sempre.", reference: "Salmos 12:7" },
    { text: "Os ímpios andam altivos por toda parte, quando a corrupção é exaltada entre os homens.", reference: "Salmos 12:8" },
    { text: "Até quando, Senhor? Para sempre te esquecerás de mim? Até quando esconderás de mim o teu rosto?", reference: "Salmos 13:1" },
    { text: "os meus inimigos dirão: \"Eu o venci\", e os meus adversários festejarão o meu fracasso.", reference: "Salmos 13:4" },
    { text: "Eu, porém, confio em teu amor; o meu coração exulta em tua salvação.", reference: "Salmos 13:5" },
    { text: "Quero cantar ao Senhor pelo bem que me tem feito.", reference: "Salmos 13:6" },
    { text: "Olhem! Estão tomados de pavor! Pois Deus está presente no meio dos justos.", reference: "Salmos 14:5" },
    { text: "Vocês, malfeitores, frustram os planos dos pobres, mas o refúgio deles é o Senhor.", reference: "Salmos 14:6" },
    { text: "Senhor, quem habitará no teu santuário? Quem poderá morar no teu santo monte?", reference: "Salmos 15:1" },
    { text: "Aquele que é íntegro em sua conduta e pratica o que é justo, que de coração fala a verdade", reference: "Salmos 15:2" },
    { text: "Protege-me, ó Deus, pois em ti me refugio.", reference: "Salmos 16:1" },
    { text: "Ao Senhor declaro: \"Tu és o meu Senhor; não tenho bem nenhum além de ti\".", reference: "Salmos 16:2" },
    { text: "Quanto aos fiéis que há na terra, eles é que são os notáveis em quem está todo o meu prazer.", reference: "Salmos 16:3" },
    { text: "As divisas caíram para mim em lugares agradáveis: Tenho uma bela herança!", reference: "Salmos 16:6" },
    { text: "Bendirei o Senhor, que me aconselha; na escura noite o meu coração me ensina!", reference: "Salmos 16:7" },
    { text: "Sempre tenho o Senhor diante de mim. Com ele à minha direita, não serei abalado.", reference: "Salmos 16:8" },
    { text: "Por isso o meu coração se alegra e no íntimo exulto; mesmo o meu corpo repousará tranqüilo,", reference: "Salmos 16:9" },
    { text: "porque tu não me abandonarás no sepulcro, nem permitirás que o teu santo sofra decomposição.", reference: "Salmos 16:10" },
    { text: "Venha de ti a sentença em meu favor; vejam os teus olhos onde está a justiça!", reference: "Salmos 17:2" },
    { text: "como fazem os homens. Pela palavra dos teus lábios eu evitei os caminhos do violento.", reference: "Salmos 17:4" },
    { text: "Meus passos seguem firmes nas tuas veredas; os meus pés não escorregaram.", reference: "Salmos 17:5" },
    { text: "Protege-me como à menina dos teus olhos; esconde-me à sombra das tuas asas,", reference: "Salmos 17:8" },
    { text: "dos ímpios que me atacam com violência, dos inimigos mortais que me cercam.", reference: "Salmos 17:9" },
    { text: "Eles fecham o coração insensível, e com a boca falam com arrogância.", reference: "Salmos 17:10" },
    { text: "Eles me seguem os passos, e já me cercam; seus olhos estão atentos, prontos para derrubar-me.", reference: "Salmos 17:11" },
    { text: "São como um leão ávido pela presa, como um leão forte agachado na emboscada.", reference: "Salmos 17:12" },
    { text: "Levanta-te, Senhor! Confronta-os! Derruba-os! Com a tua espada livra-me dos ímpios.", reference: "Salmos 17:13" },
    { text: "Clamo ao Senhor, que é digno de louvor, e estou salvo dos meus inimigos.", reference: "Salmos 18:3" },
    { text: "As cordas da morte me enredaram; as torrentes da destruição me surpreenderam.", reference: "Salmos 18:4" },
    { text: "As cordas do Sheol me envolveram; os laços da morte me alcançaram.", reference: "Salmos 18:5" },
    { text: "Das suas narinas subiu fumaça; da sua boca saíram brasas vivas e fogo consumidor.", reference: "Salmos 18:8" },
    { text: "Ele abriu os céus e desceu; nuvens escuras estavam sob os seus pés.", reference: "Salmos 18:9" },
    { text: "Montou um querubim e voou, deslizando sobre as asas do vento.", reference: "Salmos 18:10" },
    { text: "Fez das trevas o seu esconderijo, das escuras nuvens, cheias de água, o abrigo que o envolvia.", reference: "Salmos 18:11" },
    { text: "Com o fulgor da sua presença as nuvens se desfizeram em granizo e raios,", reference: "Salmos 18:12" },
    { text: "quando dos céus trovejou o Senhor, e ressoou a voz do Altíssimo.", reference: "Salmos 18:13" },
    { text: "Atirou suas flechas e dispersou os inimigos, com seus raios os derrotou.", reference: "Salmos 18:14" },
    { text: "Das alturas estendeu a mão e me segurou; tirou-me das águas profundas.", reference: "Salmos 18:16" },
    { text: "Livrou-me do meu inimigo poderoso, dos meus adversários, fortes demais para mim.", reference: "Salmos 18:17" },
    { text: "Eles me atacaram no dia da minha desgraça, mas o Senhor foi o meu amparo.", reference: "Salmos 18:18" },
    { text: "Ele me deu total libertação; livrou-me porque me quer bem.", reference: "Salmos 18:19" },
    { text: "O Senhor me tratou conforme a minha justiça; conforme a pureza das minhas mãos recompensou-me.", reference: "Salmos 18:20" },
    { text: "Pois segui os caminhos do Senhor; não agi como ímpio, afastando-me do meu Deus.", reference: "Salmos 18:21" },
    { text: "Todas as suas ordenanças estão diante de mim; não me desviei dos seus decretos.", reference: "Salmos 18:22" },
    { text: "Tenho sido irrepreensível para com ele e guardei-me de praticar o mal.", reference: "Salmos 18:23" },
    { text: "Ao fiel te revelas fiel, ao irrepreensível te revelas irrepreensível,", reference: "Salmos 18:25" },
    { text: "ao puro te revelas puro, mas com o perverso reages à altura.", reference: "Salmos 18:26" },
    { text: "Salvas os que são humildes, mas humilhas os de olhos altivos.", reference: "Salmos 18:27" },
    { text: "Tu, Senhor, manténs acesa a minha lâmpada; o meu Deus transforma em luz as minhas trevas.", reference: "Salmos 18:28" },
    { text: "Com o teu auxílio posso atacar uma tropa; com o meu Deus posso transpor muralhas.", reference: "Salmos 18:29" },
    { text: "Pois quem é Deus além do Senhor? E quem é rocha senão o nosso Deus?", reference: "Salmos 18:31" },
    { text: "Ele é o Deus que me reveste de força e torna perfeito o meu caminho.", reference: "Salmos 18:32" },
    { text: "Torna os meus pés ágeis como os da corça, sustenta-me firme nas alturas.", reference: "Salmos 18:33" },
    { text: "Ele treina as minhas mãos para a batalha e os meus braços para vergar um arco de bronze.", reference: "Salmos 18:34" },
    { text: "Deixaste livre o meu caminho, para que não se torçam os meus tornozelos.", reference: "Salmos 18:36" },
    { text: "Persegui os meus inimigos e os alcancei; e não voltei enquanto não foram destruídos.", reference: "Salmos 18:37" },
    { text: "Massacrei-os, e não puderam levantar-se; jazem debaixo dos meus pés.", reference: "Salmos 18:38" },
    { text: "Deste-me força para o combate; subjugaste os que se rebelaram contra mim.", reference: "Salmos 18:39" },
    { text: "Puseste os meus inimigos em fuga e exterminei os que me odiavam.", reference: "Salmos 18:40" },
    { text: "Eu os reduzi a pó, pó que o vento leva. Pisei-os como à lama das ruas.", reference: "Salmos 18:42" },
    { text: "Assim que me ouvem, me obedecem; são estrangeiros que se submetem a mim.", reference: "Salmos 18:44" },
    { text: "Todos eles perderam a coragem; tremendo, saem das suas fortalezas.", reference: "Salmos 18:45" },
    { text: "O Senhor vive! Bendita seja a minha Rocha! Exaltado seja Deus, o meu Salvador!", reference: "Salmos 18:46" },
    { text: "Este é o Deus que em meu favor executa vingança, que a mim sujeita nações.", reference: "Salmos 18:47" },
    { text: "Por isso eu te louvarei entre as nações, ó Senhor; cantarei louvores ao teu nome.", reference: "Salmos 18:49" },
    { text: "Um dia fala disso a outro dia; uma noite o revela a outra noite.", reference: "Salmos 19:2" },
    { text: "Sem discurso nem palavras, não se ouve a sua voz.", reference: "Salmos 19:3" },
    { text: "Sai de uma extremidade dos céus e faz o seu trajeto até a outra; nada escapa ao seu calor.", reference: "Salmos 19:6" },
    { text: "Por elas o teu servo é advertido; há grande recompensa em obedecer-lhes.", reference: "Salmos 19:11" },
    { text: "Quem pode discernir os próprios erros? Absolve-me dos que desconheço!", reference: "Salmos 19:12" },
    { text: "Que o Senhor te responda no tempo da angústia; o nome do Deus de Jacó te proteja!", reference: "Salmos 20:1" },
    { text: "Do santuário te envie auxílio e de Sião te dê apoio.", reference: "Salmos 20:2" },
    { text: "Lembre-se de todas as tuas ofertas e aceite os teus holocaustos. Pausa", reference: "Salmos 20:3" },
    { text: "Conceda-te o desejo do teu coração e leve a efeito todos os teus planos.", reference: "Salmos 20:4" },
    { text: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor nosso Deus.", reference: "Salmos 20:7" },
    { text: "Eles vacilam e caem, mas nós nos erguemos e estamos firmes.", reference: "Salmos 20:8" },
    { text: "Senhor, concede vitória ao rei! Responde-nos quando clamamos!", reference: "Salmos 20:9" },
    { text: "Tu lhe concedeste o desejo do seu coração e não lhe rejeitaste o pedido dos seus lábios. Pausa", reference: "Salmos 21:2" },
    { text: "Tu o recebeste com ricas bênçãos, e em sua cabeça puseste uma coroa de ouro puro.", reference: "Salmos 21:3" },
    { text: "Ele te pediu vida, e tu lhe deste! Vida longa e duradoura.", reference: "Salmos 21:4" },
    { text: "Pelas vitórias que lhe deste, grande é a sua glória; de esplendor e majestade o cobriste.", reference: "Salmos 21:5" },
    { text: "Fizeste dele uma grande bênção para sempre e lhe deste a alegria da tua presença.", reference: "Salmos 21:6" },
    { text: "O rei confia no Senhor: por causa da fidelidade do Altíssimo ele não será abalado.", reference: "Salmos 21:7" },
    { text: "Tua mão alcançará todos os teus inimigos; tua mão direita atingirá todos os que te odeiam.", reference: "Salmos 21:8" },
    { text: "Acabarás com a geração deles na terra, com a sua descendência entre os homens.", reference: "Salmos 21:10" },
    { text: "Embora tramem o mal contra ti e façam planos perversos, nada conseguirão;", reference: "Salmos 21:11" },
    { text: "pois tu os porás em fuga quando apontares para eles o teu arco.", reference: "Salmos 21:12" },
    { text: "Sê exaltado, Senhor, na tua força! Cantaremos e louvaremos o teu poder.", reference: "Salmos 21:13" },
    { text: "Meu Deus! Eu clamo de dia, mas não respondes; de noite, e não recebo alívio!", reference: "Salmos 22:2" },
    { text: "Tu, porém, és o Santo, és rei, és o louvor de Israel.", reference: "Salmos 22:3" },
    { text: "Em ti os nossos antepassados puseram a sua confiança; confiaram, e os livraste.", reference: "Salmos 22:4" },
    { text: "Clamaram a ti, e foram libertos; em ti confiaram, e não se decepcionaram.", reference: "Salmos 22:5" },
    { text: "Mas eu sou verme, e não homem, motivo de zombaria e objeto de desprezo do povo.", reference: "Salmos 22:6" },
    { text: "Caçoam de mim todos os que me vêem; balançando a cabeça, lançam insultos contra mim, dizendo:", reference: "Salmos 22:7" },
    { text: "\"Recorra ao Senhor! Que o Senhor o liberte! Que ele o livre, já que lhe quer bem! \"", reference: "Salmos 22:8" },
    { text: "Contudo, tu mesmo me tiraste do ventre; deste-me segurança junto ao seio de minha mãe.", reference: "Salmos 22:9" },
    { text: "Desde que nasci fui entregue a ti; desde o ventre materno és o meu Deus.", reference: "Salmos 22:10" },
    { text: "Não fiques distante de mim, pois a angústia está perto e não há ninguém que me socorra.", reference: "Salmos 22:11" },
    { text: "Muitos touros me cercam, sim, rodeiam-me os poderosos de Basã.", reference: "Salmos 22:12" },
    { text: "Como leão voraz rugindo escancaram a boca contra mim.", reference: "Salmos 22:13" },
    { text: "Cães me rodearam! Um bando de homens maus me cercou! Perfuraram minhas mãos e meus pés.", reference: "Salmos 22:16" },
    { text: "Posso contar todos os meus ossos, mas eles me encaram com desprezo.", reference: "Salmos 22:17" },
    { text: "Dividiram as minhas roupas entre si, e tiraram sortes pelas minhas vestes.", reference: "Salmos 22:18" },
    { text: "Tu, porém, Senhor, não fiques distante! Ó minha força, vem logo em meu socorro!", reference: "Salmos 22:19" },
    { text: "Livra-me da espada, livra a minha vida do ataque dos cães.", reference: "Salmos 22:20" },
    { text: "Salva-me da boca dos leões, e dos chifres dos bois selvagens. E tu me respondeste.", reference: "Salmos 22:21" },
    { text: "Proclamarei o teu nome a meus irmãos; na assembléia te louvarei.", reference: "Salmos 22:22" },
    { text: "pois do Senhor é o reino; ele governa as nações.", reference: "Salmos 22:28" },
    { text: "A posteridade o servirá; gerações futuras ouvirão falar do Senhor,", reference: "Salmos 22:30" },
    { text: "Em verdes pastagens me faz repousar e me conduz a águas tranqüilas;", reference: "Salmos 23:2" },
];

export function getDailyWord() {
    const dayOfYear = Math.floor((new Date().getTime() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
    return dailyWords[Math.floor(dayOfYear) % dailyWords.length];
}
